"use strict";

exports.__esModule = true;
var modal_main = exports.modal_main = "bottom: 0;\n                           left: 0;\n                           position: absolute;\n                           right: 0;\n                           top: 0;\n                           -webkit-box-align: center;\n                                 -ms-flex-align: center;\n                                     align-items: center;\n                           display: none;\n                           -webkit-box-orient: vertical;\n                           -webkit-box-direction: normal;\n                               -ms-flex-direction: column;:%\n                                   flex-direction: column;\n                           -webkit-box-pack: center;\n                               -ms-flex-pack: center;\n                                   justify-content: center;\n                           overflow: hidden;\n                           position: fixed;\n                           z-index: 500000;\n                           display: -webkit-box;\n                           display: -ms-flexbox;\n                           display: flex;";

var modal_background = exports.modal_background = "bottom: 0;\n                                  left: 0;\n                                  position: absolute;\n                                  right: 0;\n                                  top: 0;\n                                  background-color: rgba(10, 10, 10, 0.86); }";

var modal_card = exports.modal_card = "margin: 0 20px;\n                            height: 820px;\n                            overflow: auto;\n                            position: relative;\n                            width: 600px;\n                            max-height: 95vh;\n                            display: -webkit-box;\n                            display: -ms-flexbox;\n                            display: flex;\n                            border-radius: 5px;\n                            -webkit-box-orient: vertical;\n                            -webkit-box-direction: normal;\n                                -ms-flex-direction: column;\n                                    flex-direction: column;\n                            background-color: white;\n                            -ms-overflow-y: visible;";

var modal_head = exports.modal_head = "-webkit-box-align: center;\n                                 -ms-flex-align: center;\n                                     align-items: center;\n                             background-color: white;\n                             display: -webkit-box;\n                             display: -ms-flexbox;\n                             display: flex;\n                             -ms-flex-negative: 0;\n                                 flex-shrink: 0;\n                             -webkit-box-pack: start;\n                                 -ms-flex-pack: start;\n                                     justify-content: center;\n                             padding: 20px;\n                             position: relative;\n                             border-bottom: 1px solid #dbdbdb;\n                             border-top-left-radius: 6px;\n                             border-top-right-radius: 6px;";