export const modal_main = `bottom: 0;
                           left: 0;
                           position: fixed;
                           right: 0;
                           top: 0;
                           -webkit-box-align: center;
                                 -ms-flex-align: center;
                                     align-items: center;
                           display: none;
                           -webkit-box-orient: vertical;
                           -webkit-box-direction: normal;
                               -ms-flex-direction: column;:%
                                   flex-direction: column;
                           -webkit-box-pack: center;
                               -ms-flex-pack: center;
                                   justify-content: center;
                           overflow: hidden;
                           position: fixed;
                           z-index: 500000;
                           display: -webkit-box;
                           display: -ms-flexbox;
                           display: flex;`;

export const modal_background = `bottom: 0;
                                  left: 0;
                                  position: absolute;
                                  right: 0;
                                  top: 0;
                                  background-color: rgba(10, 10, 10, 0.86); }`;

export const modal_card = `margin: 0 20px;
                            height: 820px;
                            overflow: auto;
                            position: relative;
                            width: 600px;
                            max-height: 95vh;
                            display: -webkit-box;
                            display: -ms-flexbox;
                            display: flex;
                            border-radius: 5px;
                            -webkit-box-orient: vertical;
                            -webkit-box-direction: normal;
                                -ms-flex-direction: column;
                                    flex-direction: column;
                            -webkit-overflow-scrolling: touch;
                            overflow-y: scroll
                            background-color: white;
                            -ms-overflow-y: visible;`;

export const modal_card_mobile = `margin: 0;
                                  height: 100vh;
                                  max-height: 100vh;
                                  overflow: auto;
                                  position: relative;
                                  width: 100vw;
                                  display: -webkit-box;
                                  display: -ms-flexbox;
                                  display: flex;
                                  -webkit-box-orient: vertical;
                                  -webkit-box-direction: normal;
                                      -ms-flex-direction: column;
                                          flex-direction: column;
                                  -webkit-overflow-scrolling: touch;
                                  overflow-y: scroll
                                  background-color: white;
                                  -ms-overflow-y: visible;`;

export const modal_head = `-webkit-box-align: center;
                                 -ms-flex-align: center;
                                     align-items: center;
                             background-color: white;
                             display: -webkit-box;
                             display: -ms-flexbox;
                             display: flex;
                             -ms-flex-negative: 0;
                                 flex-shrink: 0;
                             -webkit-box-pack: start;
                                 -ms-flex-pack: start;
                                     justify-content: center;
                             padding: 20px;
                             position: relative;
                             border-bottom: 1px solid #dbdbdb;
                             border-top-left-radius: 6px;
                             border-top-right-radius: 6px;`;
